language: python

python:
  - "3.4"
  - "2.7"

env:
  - DJANGO=1.7
  - DJANGO=1.8
  - DJANGO=1.9

cache:
  - pip

install:
  - pip install django==$DJANGO six pep8 pyflakes

before_script:
  - "pep8 --ignore=E128,E501 templated_email"
  - "pyflakes templated_email"

script:
  - python manage.py test --verbosity=2

after_script:
  # remove the debug log so we don't update the cache for no reason
  - rm $HOME/.cache/pip/log/debug.log